version: '3.8'

services:
  # apache:
  #   container_name: apache
  #   build: ./docker/apache
  #   # links:
  #   #   - php80
  #   networks:
  #     - lamp
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./htdocs:/usr/local/apache2/htdocs
  #     - ./docker/apache/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
  nginx:
    container_name: nginx
    build: ./docker/nginx
    ports: 
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www/html
    networks:
      - lnmp
    profiles:
      - php80
      - php74

  php80:
    container_name: php80
    build: ./docker/php80
    networks:
      - lnmp
    ports:
      - "9000:9000"
    volumes:
      - ./www:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql8
    profiles:
      - php80

  php74:
    container_name: php74
    build: ./docker/php74
    networks:
      - lnmp
    ports:
      - "9000:9000"
    volumes:
      - ./www:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql8
    profiles:
      - php74

  mysql8:
    image: mysql:8.0.28
    container_name: mysql8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: jason
      MYSQL_USER: jason
      MYSQL_PASSWORD: jason
    ports:
      - "3306:3306"
    networks:
      - lnmp
    volumes:
      - ./docker/mysql8:/var/lib/mysql
    profiles:
      - php80
      - php74

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: pma
    networks:
      - lnmp
    environment:
      PMA_HOST: mysql8
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 300M
    restart: always
    ports:
      - 8085:80
    depends_on:
      - mysql8
    profiles:
      - php80
      - php74
networks:
    lnmp:
